---
name: Dns/Dhcp Server
version: 1.2.0
stage: stable
slug: dns
description: >-
  Self host a Dns/Dhcp server for privacy & security
url: https://github.com/rolbre/hassio-addons/tree/main/dns
arch:
  - amd64
  - armv7
  - aarch64
codenotary: breitschaftroland@gmail.com
host_network: true
startup: system
homeassistant: 2022.11.0
init: false
advanced: true
apparmor: true
panel_admin: true
backup: hot
backup_exclude:
  - "/data/config/logs/*.log"
  - "/data/config/stats/*.stat"
  - "/data/config/stats/*.dstat"
watchdog: tcp://[HOST]:53
ports:
  53/tcp: 53
  53/udp: 53
  67/udp: 67
  68/udp: 68
  5380/tcp: 5380
  8053/tcp: 8053
  853/tcp: null
  80/tcp: null
  443/tcp: null
options:
  domain: homeassistant.local
  admin_password: null
  forwarders: null
  local_time: true
  dns_over_http: true
  log_level: info
schema:
  domain: str
  admin_password: password
  prefer_ipv6: bool?
  dns_over_http: bool?
  recursion: list(Allow|Deny|AllowOnlyForPrivateNetworks|UseSpecifiedNetworks)?
  recursion_denied_networks: str?
  recursion_allowed_networks: str?
  enable_blocking: bool?
  allow_txt_blocking_report: bool?
  block_list_urls: str?
  forwarders: str
  forwarder_protocol: list(Udp|Tcp|Tls|Https|HttpsJson)
  local_time: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
