---
name: MongoDB
version: 1.0.1
stage: stable
slug: mongodb
description: >-
  MongoDB is a source-available, cross-platform, document-oriented database program
url: https://github.com/danlorb/hassio-addons/tree/main/mongodb
arch:
  - amd64
  - aarch64
codenotary: breitschaftroland@gmail.com
host_network: true
startup: system
init: false
advanced: true
apparmor: true
homeassistant: 2025.05.5
panel_admin: true
backup: hot
ports:
  27017/tcp: 27017
options:  
  log_level: info
schema:  
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
